/**
 * One-time script to generate lib/school-domains.ts from the CSV data.
 * Extracts the most common .edu domain per school name from coach emails.
 *
 * Usage: npx tsx scripts/generate-school-domains.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const CSV_PATH = join(__dirname, "..", "data", "final_corrected_schools.csv");
const OUTPUT_PATH = join(__dirname, "..", "lib", "school-domains.ts");

function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      result.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

function extractRootDomain(email: string): string | null {
  const atIndex = email.indexOf("@");
  if (atIndex === -1) return null;
  const domain = email.slice(atIndex + 1).toLowerCase().trim();
  if (!domain) return null;
  return domain;
}

const csv = readFileSync(CSV_PATH, "utf-8");
const lines = csv.split("\n").filter((l) => l.trim());
const header = parseCSVLine(lines[0]);

const schoolIdx = header.indexOf("School");
const emailIdx = header.indexOf("Email");

if (schoolIdx === -1 || emailIdx === -1) {
  console.error("Could not find School or Email columns in CSV");
  process.exit(1);
}

// Count domain occurrences per school
const schoolDomainCounts = new Map<string, Map<string, number>>();

for (let i = 1; i < lines.length; i++) {
  const cols = parseCSVLine(lines[i]);
  const school = cols[schoolIdx];
  const email = cols[emailIdx];

  if (!school || !email) continue;

  const domain = extractRootDomain(email);
  if (!domain) continue;

  if (!schoolDomainCounts.has(school)) {
    schoolDomainCounts.set(school, new Map());
  }
  const counts = schoolDomainCounts.get(school)!;
  counts.set(domain, (counts.get(domain) || 0) + 1);
}

// Pick the most common domain for each school, preferring .edu domains
const schoolDomains = new Map<string, string>();

for (const [school, domainCounts] of schoolDomainCounts) {
  let bestDomain = "";
  let bestCount = 0;
  let bestIsEdu = false;

  for (const [domain, count] of domainCounts) {
    const isEdu = domain.endsWith(".edu");
    // Prefer .edu domains, then highest count
    if (
      (!bestIsEdu && isEdu) ||
      (isEdu === bestIsEdu && count > bestCount)
    ) {
      bestDomain = domain;
      bestCount = count;
      bestIsEdu = isEdu;
    }
  }

  if (bestDomain) {
    schoolDomains.set(school, bestDomain);
  }
}

// Manual overrides for schools without .edu emails
const manualOverrides: Record<string, string> = {
  "Montana State University-Bozeman": "montana.edu",
  "Rutgers, The State University of New Jersey, New Brunswick": "rutgers.edu",
  "Simon Fraser University": "sfu.ca",
  "University of Louisville": "louisville.edu",
  "University of Nebraska, Lincoln": "unl.edu",
  "Wichita State University": "wichita.edu",
};

for (const [school, domain] of Object.entries(manualOverrides)) {
  if (!schoolDomains.has(school) || !schoolDomains.get(school)!.endsWith(".edu")) {
    schoolDomains.set(school, domain);
  }
}

// Sort and generate output
const sorted = Array.from(schoolDomains.entries()).sort((a, b) =>
  a[0].localeCompare(b[0])
);

const entries = sorted
  .map(([school, domain]) => `  ${JSON.stringify(school)}: ${JSON.stringify(domain)},`)
  .join("\n");

const output = `// Auto-generated by scripts/generate-school-domains.ts
// Maps school names to their primary web domain for logo fetching.
// Total: ${sorted.length} schools

export const SCHOOL_DOMAINS: Record<string, string> = {
${entries}
};
`;

writeFileSync(OUTPUT_PATH, output, "utf-8");
console.log(`Generated ${OUTPUT_PATH} with ${sorted.length} school domain mappings.`);

// Report any schools without a domain
const allSchools = new Set<string>();
for (let i = 1; i < lines.length; i++) {
  const cols = parseCSVLine(lines[i]);
  const school = cols[schoolIdx];
  if (school) allSchools.add(school);
}

const missing = Array.from(allSchools).filter((s) => !schoolDomains.has(s));
if (missing.length > 0) {
  console.log(`\nSchools without domain mapping (${missing.length}):`);
  missing.forEach((s) => console.log(`  - ${s}`));
}
